

[using] common [/using]

[export]


	### Common Operators ###

	[namespace common]

		pair ( a, b ) : { { a }, { a, b } }

		###left ( p ) : {  }###

		union        : ∪
		intersection : ∩
		difference   : \
		complement   : \
		powerset     : ℙ


		c(a, b) : a + b

	[/namespace]

	[namespace mathematics]

		a(n) : #(a) + 2

	[/namespace]

	### 
	Another
	Comment 
	Block ###

[/export]



union(  )